# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: MyHass.io
version: "1.0.6"
slug: myhass
description: Home Assistant secure remote access
url: "https://github.com/MyHass-io/homeassistant-app-public"
arch:
  - aarch64
  - amd64
init: false
startup: services
options:
  nodeId: ""
  secret: ""
  #email: ""
  #password: ""
schema:
  nodeId: "str?"
  secret: "str?"
  #email: "str?"
  #password: "str?"
image: "ghcr.io/myhass-io/{arch}-addon-myhass"
apparmor: true
host_network: true

